### ISSUE TITLE
Upload artifacts for each build

### ISSUE THREAD

**Issue by yeswolf** [SuduIDE/ij-struct-view-layout#5]
Something like

```
 - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: plugin_package-${{ github.run_number }}
        path: <path to plugin.zip>
```

Don't mix with releases - this section is just to have unstable builds available to check the current progress.
